// Mirrors backend/Config.js enums and HEADERS — field names match the Sheet
// columns exactly (feature 006 data-model.md).

export type Owner = 'max' | 'jaz' | 'both'
export type TaskStatus = 'open' | 'done' | 'snoozed'
export type Cadence = 'weekly' | 'biweekly' | 'monthly' | 'sixweekly' | 'eightweekly' | 'quarterly' | 'annually' | 'semiannually' | 'thanksgiving-sat'

export interface Event {
  id: string
  title: string
  start: string // ISO 8601 datetime, or YYYY-MM-DD for an all-day event
  end: string // ISO 8601 datetime, or YYYY-MM-DD for an all-day event
  owner: Owner
  type?: string
  notes?: string
  templateId?: string
  gcalEventId?: string
  prepGeneratedFor?: string
  location?: string
  recurringEventId?: string // feature 025: set on occurrences generated by a RecurringEventRule
}

export interface Task {
  id: string
  title: string
  dueDate?: string // ISO date
  owner: Owner
  status: TaskStatus
  eventId?: string
  recurringId?: string
  completedBy?: Owner
  completedAt?: string // ISO datetime
  snoozeHistory?: string
  listItems?: string
  notes?: string
  ackBy?: Owner // feature 019: who committed to this assignment
  ackAt?: string // ISO datetime
  somedayRank?: string // feature 021: shared household priority order; blank = unranked
}

export interface Settings {
  timezone: string
  [key: string]: string
}

// Feature 024 — grocery & household lists. No owner field: every list/item is
// implicitly shared, unlike Tasks/Events (research R2).
export type ListItemStatus = 'need' | 'stocked'
export type ListSection = 'produce' | 'dairy' | 'frozen' | 'pantry' | 'household' | 'other' | ''

export interface List {
  id: string
  name: string
}

export interface ListItem {
  id: string
  listId: string
  name: string
  status: ListItemStatus
  section: ListSection
  staple: 'TRUE' | 'FALSE'
  note?: string
  /** Feature 034 US3: household-tz timestamp of the last time this item was marked stocked
   *  (server-managed); absent/empty until first stocked. */
  stockedAt?: string
}

export interface RecurringRule {
  id: string
  title: string
  cadence: Cadence
  anchorDate: string     // YYYY-MM-DD
  defaultOwner: Owner
  lastGenerated?: string // YYYY-MM-DD
  seasonStart?: string   // '1'–'12'
  seasonEnd?: string     // '1'–'12'
}

// Feature 025 — recurring events: full cadence parity with RecurringRule, but
// materializes Events (via a nightly generator) instead of Tasks.
export interface RecurringEventRule {
  id: string
  title: string
  cadence: Cadence
  anchorDate: string       // YYYY-MM-DD
  startTime?: string       // HH:mm; blank ⇒ all-day occurrences
  durationMinutes?: string // minutes; only meaningful with startTime set
  defaultOwner: Owner
  templateId?: string      // attaches a prep-checklist template (TaskTemplate.eventType)
  location?: string
  notes?: string
  lastGenerated?: string   // YYYY-MM-DD
  seasonStart?: string     // '1'–'12'
  seasonEnd?: string       // '1'–'12'
}

export interface TaskTemplate {
  id: string
  eventType: string
  taskTitle: string
  offsetDays: number     // int; negative = before event, 0 = day-of, positive = after
  defaultOwner: Owner
}

export interface ActivityEntry {
  id?: string
  timestamp: string // ISO datetime
  // Live data showed values beyond the two people ('system' for digests/push/dog-walk
  // moves, 'selftest' for backend self-test runs) — treat as an open string, not a closed
  // union (feature 032 US2, audit F-09); `activityActorStyle` (lib/owners.ts) is the single
  // place that maps an unrecognized actor to a safe fallback badge.
  actor: 'max' | 'jaz' | (string & {})
  action: string
  targetId?: string
  detail?: string
  summary: string // composed human-readable sentence from backend
}

export interface WhoAmI {
  identity: 'max' | 'jaz' | 'shared'
  displayName: string
  email: string
  needsActingPerson: boolean
  /** Backend-minted household session token (018 rev.) — fresh on every whoami. */
  sessionToken: string
}

export interface Session {
  token: string
  who: WhoAmI
  actingPerson?: 'max' | 'jaz'
}

// Feature 011 — weather-aware dog-walk finder (contracts/dogwalks-api.md). Read-only in
// 011/029; feature 031 US3 adds a write path (dogwalks.book/unbook/release) and the
// 'skipped' status (a user removed the walk — distinct from 'needs-decision', where the
// finder itself couldn't decide; data-model.md §1).
export type DogWalkStatus = 'booked' | 'suggested' | 'needs-decision' | 'deferred' | 'skipped'

export interface DogWalk {
  id: string
  date: string // YYYY-MM-DD
  slot: 'primary' | 'second'
  status: DogWalkStatus
  windowStart: string | null // ISO datetime
  windowEnd: string | null // ISO datetime
  durationMin: number | null
  reason: string | null // set for needs-decision
  // Feature 031 US3: who made this decision by hand — max/jaz, or null when the finder owns
  // the row and may move/replace/flag it freely (data-model §1).
  decidedBy?: 'max' | 'jaz' | null
}

// Feature 031 — dog-walk day planner (contracts/dogwalks-planner-api.md `dogwalks.day`).
// Assembled server-side from the finder engine's own functions, so it cannot drift from
// what the nightly run decides (FR-015) — the frontend only ever renders this, never
// recomputes gates or window selection itself.
export interface ForecastProvenance {
  source: 'live' | 'cache' | 'none'
  fetchedAt: string | null // ISO datetime, household tz offset; null when source is 'none'
  ageMinutes: number | null
  usableForBooking: boolean // false once the cache is older than the 24h freshness limit (FR-006)
  reliable: boolean // false when the date falls beyond the reliable-forecast horizon (FR-013)
}

export type WeatherGateName = 'heat' | 'cold' | 'precip' | 'snowIce' | 'noForecast'

export interface BusyBlock {
  start: string // ISO datetime
  end: string // ISO datetime
  owner: Owner
  title: string | null // null when the source event is private/free-busy-only
}

export interface HourGate {
  hour: string // 'YYYY-MM-DDTHH'
  tempF: number | null
  precipProbPct: number | null
  wmoCode: number | null
  passes: boolean
  failedGates: WeatherGateName[]
}

export interface CandidateWindow {
  start: string // ISO datetime
  end: string // ISO datetime
  durationMin: number
  chosen: boolean
  slot: 'primary' | 'second'
}

export interface DogWalkDayPlan {
  date: string // YYYY-MM-DD
  forecast: ForecastProvenance
  calendarsReadable: boolean // false when a source calendar threw (FR-014) — busyBlocks is then incomplete
  busyBlocks: BusyBlock[]
  hours: HourGate[]
  candidates: CandidateWindow[]
  walks: DogWalk[]
  // Feature 031 US3 (contract deviation — see dogwalks-planner-api.md): the configured
  // durations, needed to book an hour that has no gate-passing candidate at all.
  primaryDurationsMin: number[]
  secondDurationMin: number
}
