// Mirrors backend/Config.js enums and HEADERS — field names match the Sheet
// columns exactly (feature 006 data-model.md).

export type Owner = 'max' | 'jaz' | 'both'
export type TaskStatus = 'open' | 'done' | 'snoozed'
export type Cadence = 'weekly' | 'biweekly' | 'monthly' | 'sixweekly' | 'eightweekly' | 'quarterly' | 'annually' | 'semiannually' | 'thanksgiving-sat'

export interface Event {
  id: string
  title: string
  start: string // ISO 8601 datetime, or YYYY-MM-DD for an all-day event
  end: string // ISO 8601 datetime, or YYYY-MM-DD for an all-day event
  owner: Owner
  type?: string
  notes?: string
  templateId?: string
  gcalEventId?: string
  prepGeneratedFor?: string
  location?: string
  recurringEventId?: string // feature 025: set on occurrences generated by a RecurringEventRule
}

export interface Task {
  id: string
  title: string
  dueDate?: string // ISO date
  owner: Owner
  status: TaskStatus
  eventId?: string
  recurringId?: string
  completedBy?: Owner
  completedAt?: string // ISO datetime
  snoozeHistory?: string
  listItems?: string
  notes?: string
  ackBy?: Owner // feature 019: who committed to this assignment
  ackAt?: string // ISO datetime
  somedayRank?: string // feature 021: shared household priority order; blank = unranked
}

export interface Settings {
  timezone: string
  [key: string]: string
}

// Feature 024 — grocery & household lists. No owner field: every list/item is
// implicitly shared, unlike Tasks/Events (research R2).
export type ListItemStatus = 'need' | 'stocked'
export type ListSection = 'produce' | 'dairy' | 'frozen' | 'pantry' | 'household' | 'other' | ''

export interface List {
  id: string
  name: string
}

export interface ListItem {
  id: string
  listId: string
  name: string
  status: ListItemStatus
  section: ListSection
  staple: 'TRUE' | 'FALSE'
  note?: string
}

export interface RecurringRule {
  id: string
  title: string
  cadence: Cadence
  anchorDate: string     // YYYY-MM-DD
  defaultOwner: Owner
  lastGenerated?: string // YYYY-MM-DD
  seasonStart?: string   // '1'–'12'
  seasonEnd?: string     // '1'–'12'
}

// Feature 025 — recurring events: full cadence parity with RecurringRule, but
// materializes Events (via a nightly generator) instead of Tasks.
export interface RecurringEventRule {
  id: string
  title: string
  cadence: Cadence
  anchorDate: string       // YYYY-MM-DD
  startTime?: string       // HH:mm; blank ⇒ all-day occurrences
  durationMinutes?: string // minutes; only meaningful with startTime set
  defaultOwner: Owner
  templateId?: string      // attaches a prep-checklist template (TaskTemplate.eventType)
  location?: string
  notes?: string
  lastGenerated?: string   // YYYY-MM-DD
  seasonStart?: string     // '1'–'12'
  seasonEnd?: string       // '1'–'12'
}

export interface TaskTemplate {
  id: string
  eventType: string
  taskTitle: string
  offsetDays: number     // int; negative = before event, 0 = day-of, positive = after
  defaultOwner: Owner
}

export interface ActivityEntry {
  id?: string
  timestamp: string // ISO datetime
  actor: 'max' | 'jaz'
  action: string
  targetId?: string
  detail?: string
  summary: string // composed human-readable sentence from backend
}

export interface WhoAmI {
  identity: 'max' | 'jaz' | 'shared'
  displayName: string
  email: string
  needsActingPerson: boolean
  /** Backend-minted household session token (018 rev.) — fresh on every whoami. */
  sessionToken: string
}

export interface Session {
  token: string
  who: WhoAmI
  actingPerson?: 'max' | 'jaz'
}

// Feature 011 — weather-aware dog-walk finder (contracts/dogwalks-api.md). Read-only:
// the backend engine owns all writes; the app only ever lists.
export type DogWalkStatus = 'booked' | 'suggested' | 'needs-decision' | 'deferred'

export interface DogWalk {
  id: string
  date: string // YYYY-MM-DD
  slot: 'primary' | 'second'
  status: DogWalkStatus
  windowStart: string | null // ISO datetime
  windowEnd: string | null // ISO datetime
  durationMin: number | null
  reason: string | null // set for needs-decision
}
